// Import necessary modules
const express = require("express");
const mongoose = require("mongoose");
const bodyParser = require("body-parser");
const path = require("path");

const app = express();
const port = 5000;

// Middleware
app.use(bodyParser.json());

// Connect to MongoDB
mongoose.connect("mongodb://127.0.0.1:27017/HumanResourceDatabase", {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

// Create a Mongoose schema for EmployeeCredentials
const employeecredentialsSchema = new mongoose.Schema({
  email: String,
  password: String,
});

// Create a Mongoose model
const EmployeeCredentials = mongoose.model(
    "EmployeeCredentials",
    employeecredentialsSchema,
    "employeecredentials" // Specify the collection name
  );

// API endpoint to handle form submissions
app.post("/api/createAccount", async (req, res) => {
  try {
    const { email, password } = req.body;

    // Create a new document in the EmployeeCredentials collection
    const newEmployee = new EmployeeCredentials({ email, password });
    await newEmployee.save();

    res.status(200).json({ success: true, message: "Account created successfully" });
  } catch (error) {
    console.error("Error creating account:", error);
    res.status(500).json({ success: false, error: "Internal Server Error" });
  }
});

// Serve static files for a React app (if applicable)
// This assumes you have a build folder generated by `npm run build`
app.use(express.static("build"));

// Define a catch-all route for React app (if applicable)
// This should come after all other routes
app.get("*", (req, res) => {
    res.sendFile(path.resolve(__dirname, "../build", "index.html"));
});

// Start the server
app.listen(port, () => {
  console.log(`Server is running on port ${port}`);
});
